language: java

jdk:
  - oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_d4a7eb0181c9_key -iv $encrypted_d4a7eb0181c9_iv -in settings.xml.enc -out settings.xml -d
- mv settings.xml ~/.m2/settings.xml

script: 
- cd org.uqbar.project.wollok.releng/ 
- export PROFILES=normalProfile
- if [ $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "dev" ] ; then export PROFILES="uploadRepo,uploadProducts"; export UPDATE_SITE="dev" ; fi
- if [ $TRAVIS_PULL_REQUEST == "false" -a $TRAVIS_BRANCH == "dev-natives-to-wollok" ] ; then export PROFILES="uploadRepo,uploadProducts"; export UPDATE_SITE="dev-natives-to-wollok" ;fi
- if [ $TRAVIS_PULL_REQUEST == "false" ] && [[ "$TRAVIS_TAG" =~ ^v[0-9.]* ]] ; then export PROFILES="uploadRepo,uploadProducts"; export UPDATE_SITE="stable" ; fi
- echo "Running with profiles $PROFILES"
- mvn -DupdateSiteFolder=$UPDATE_SITE -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID clean install jacoco:report coveralls:report -P $PROFILES

notifications:
  webhooks:
    urls:
    - env.GITTER_URL
    on_success: change
    on_failure: always
    on_start: false

cache:
  directories:
  - $HOME/.m2
