name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Maven Build
        run: | 
          export DISPLAY=:99.0
          echo COVERALLS_TOKEN ${{ secrets.COVERALLS_TOKEN }}
          sudo apt-get install -y xvfb
          ./wollokInstall.sh
          cd org.uqbar.project.wollok.releng/
          export PROFILES=normalProfile
          export UPDATE_SITE=none
          echo "Running with profiles $PROFILES"
          echo "Running with UPDATE_SITE $UPDATE_SITE"
          export MAVEN_OPTS=-Xmx2048m
          xvfb-run mvn -e -Darguments='-Dtycho.disableP2Mirrors=false' \
           -D tycho.disableP2Mirrors=false -U \
           -D repoToken=${{ secrets.COVERALLS_TOKEN }} \
           -D serviceName=github \
           -D serviceBuildUrl=https://github.com/${{ github.repository }}/commit/${{ github.sha }}/checks \
           -D branch=$BRANCH_NAME \
           clean install jacoco:report \
           coveralls:report \
           --no-transfer-progress \
           -P $PROFILES
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}